// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkfvVFteE5Hlh3gjXVZfhHlVKorAXuPc',
    appId: '1:797081624587:web:eb84174c3b9ee9e474a70e',
    messagingSenderId: '797081624587',
    projectId: 'chat-app-thyme',
    authDomain: 'chat-app-thyme.firebaseapp.com',
    storageBucket: 'chat-app-thyme.firebasestorage.app',
    measurementId: 'G-M8QKEHSH4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3QTtmURWPuPwMrYZfDLeL0LRgQcCFBo',
    appId: '1:797081624587:android:53925653945ac58f74a70e',
    messagingSenderId: '797081624587',
    projectId: 'chat-app-thyme',
    storageBucket: 'chat-app-thyme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZtwRnoiI4Hpe3QsB2yAuMINA3Z5WnLA',
    appId: '1:797081624587:ios:688def2acb61f8b374a70e',
    messagingSenderId: '797081624587',
    projectId: 'chat-app-thyme',
    storageBucket: 'chat-app-thyme.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZtwRnoiI4Hpe3QsB2yAuMINA3Z5WnLA',
    appId: '1:797081624587:ios:688def2acb61f8b374a70e',
    messagingSenderId: '797081624587',
    projectId: 'chat-app-thyme',
    storageBucket: 'chat-app-thyme.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkkfvVFteE5Hlh3gjXVZfhHlVKorAXuPc',
    appId: '1:797081624587:web:59cc347c2cadfcd474a70e',
    messagingSenderId: '797081624587',
    projectId: 'chat-app-thyme',
    authDomain: 'chat-app-thyme.firebaseapp.com',
    storageBucket: 'chat-app-thyme.firebasestorage.app',
    measurementId: 'G-JEK4WPN9TR',
  );
}
